export const SliderOurCategory = [
    {
        image: '../assets/images/services/service1.jpg',
        title_ru: 'Департамент проектирования объектов',
        title_uz: 'Департамент проектирования объектов',
        title_oz: 'Департамент проектирования объектов',
        title_en: 'Департамент проектирования объектов',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service2.jpg',
        title_ru: 'Департамент геологии и разработки месторождений',
        title_uz: 'Департамент геологии и разработки месторождений',
        title_oz: 'Департамент геологии и разработки месторождений',
        title_en: 'Департамент геологии и разработки месторождений',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service3.jpg',
        title_ru: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_uz: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_oz: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_en: 'Департамент подготовки и углублённой переработки нефти и газа',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service4.jpg',
        title_ru: 'Департамент экономики и финансов',
        title_uz: 'Департамент экономики и финансов',
        title_oz: 'Департамент экономики и финансов',
        title_en: 'Департамент экономики и финансов',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service5.jpg',
        title_ru: 'Подразделения по общим вопросам',
        title_uz: 'Подразделения по общим вопросам',
        title_oz: 'Подразделения по общим вопросам',
        title_en: 'Подразделения по общим вопросам',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service4.jpg',
        title_ru: 'Аппарат управления и вспомогательные подразделения',
        title_uz: 'Аппарат управления и вспомогательные подразделения',
        title_oz: 'Аппарат управления и вспомогательные подразделения',
        title_en: 'Аппарат управления и вспомогательные подразделения',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
]

export const sliderClient = [
    {
        image: "../assets/images/1.jpg",
        fullName_ru: "Искандер Равилевич Сунгатуллин",
        fullName_uz: "Искандер Равилевич Сунгатуллин",
        fullName_oz: "Iskander Ravilevich Sungatullin",
        fullName_en: "Iskander Ravilevich Sungatullin",
        position_ru: "Председатель совета директоров НИПИ «ПЕГАЗ»",
        position_uz: "НИПИ ПEГАЗ директорлар кенгаши раиси",
        position_oz: "NIPI PEGAZ direktorlar kengashi raisi",
        position_en: "Chairman of the Board of Directors of NIPI PEGAZ",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    },
    {
        image: "../assets/images/client1.png",
        fullName_ru: "Дацковский Евгений Викторович",
        fullName_uz: "Дацковский Евгений Викторович",
        fullName_oz: "Datskovskiy Yevgeniy Viktorovich",
        fullName_en: "Datskovskiy Yevgeniy Viktorovich",
        position_ru: "Генеральный директор ООО «Центр горизонтального бурения»",
        position_uz: "Генеральный директор ООО «Центр горизонтального бурения»",
        position_oz: "Генеральный директор ООО «Центр горизонтального бурения»",
        position_en: "General Director of Horizontal Drilling Center LLC",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    },
    {
        image: "../assets/images/3.jpg",
        fullName_ru: "Максим Юрьевич Недзвецкий",
        fullName_uz: "Максим Юрьевич Недзвецкий",
        fullName_oz: "Maksim Yurevich Nedzvetskiy",
        fullName_en: "Maksim Yurevich Nedzvetskiy",
        position_ru: "Генеральный директор ООО «Газпром ВНИИГАЗ»",
        position_uz: "\"Газпром ВНИИГАЗ\" МЧЖ бош директори",
        position_oz: "\"Gazprom VNIIGAZ\" MChJ bosh direktori",
        position_en: "General Director of Gazprom VNIIGAZ LLC",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    },
    {
        image: "../assets/images/4.jpg",
        fullName_ru: "Даи Ҳоулианг",
        fullName_uz: "Даи Ҳоулианг",
        fullName_oz: "Dai Houliang",
        fullName_en: "Dai Houliang",
        position_ru: "Председатель CNPC, Председатель PetroChina",
        position_uz: "CНПC раиси, ПетроЧина раиси",
        position_oz: "CNPC raisi, PetroChina raisi",
        position_en: "Chairman of CNPC, Chairman of PetroChina",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    },
    {
        image: "../assets/images/5.jpg",
        fullName_ru: "Купрыгин Олег Викторович",
        fullName_uz: "Купрыгин Олег Викторович",
        fullName_oz: "Kuprygin Oleg Viktorovich",
        fullName_en: "Kuprygin Oleg Viktorovich",
        position_ru: "Председатель Правления ЧАО «ТУРБОГАЗ»",
        position_uz: "“ТУРБОГАЗ” ХАЖ бошқаруви раиси",
        position_oz: "“TURBOGAZ” XAJ boshqaruvi raisi",
        position_en: "Chairman of the Board of PJSC \"TURBOGAZ\"",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    }
]

