export const SliderOurCategory = [
    {
        image: '../assets/images/services/service1.jpg',
        title_ru: 'Департамент проектирования объектов',
        title_uz: 'Департамент проектирования объектов',
        title_oz: 'Департамент проектирования объектов',
        title_en: 'Департамент проектирования объектов',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service2.jpg',
        title_ru: 'Департамент геологии и разработки месторождений',
        title_uz: 'Департамент геологии и разработки месторождений',
        title_oz: 'Департамент геологии и разработки месторождений',
        title_en: 'Департамент геологии и разработки месторождений',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service3.jpg',
        title_ru: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_uz: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_oz: 'Департамент подготовки и углублённой переработки нефти и газа',
        title_en: 'Департамент подготовки и углублённой переработки нефти и газа',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service4.jpg',
        title_ru: 'Департамент экономики и финансов',
        title_uz: 'Департамент экономики и финансов',
        title_oz: 'Департамент экономики и финансов',
        title_en: 'Департамент экономики и финансов',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service5.jpg',
        title_ru: 'Подразделения по общим вопросам',
        title_uz: 'Подразделения по общим вопросам',
        title_oz: 'Подразделения по общим вопросам',
        title_en: 'Подразделения по общим вопросам',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
    {
        image: '../assets/images/services/service4.jpg',
        title_ru: 'Аппарат управления и вспомогательные подразделения',
        title_uz: 'Аппарат управления и вспомогательные подразделения',
        title_oz: 'Аппарат управления и вспомогательные подразделения',
        title_en: 'Аппарат управления и вспомогательные подразделения',
        text_ru: 'подробнее',
        text_uz: 'подробнее',
        text_oz: 'подробнее',
        text_en: 'подробнее',
    },
]

export const sliderClient = [
    {
        image: "../assets/images/client1.png",
        fullName_ru: "Закари Фармер",
        fullName_uz: "Зачари Фермер",
        fullName_oz: "Zachari Fermer",
        fullName_en: "Zachary Farmer",
        position_ru: "разработчик",
        position_uz: "дастурчи",
        position_oz: "dasturchi",
        position_en: "developer",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    },
    {
        image: "../assets/images/client2.png",
        fullName_ru: "Долор Дейл",
        fullName_uz: "Долор Дейл",
        fullName_oz: "Dolor Deyl",
        fullName_en: "dolor dale",
        position_ru: "разработчик",
        position_uz: "дастурчи",
        position_oz: "dasturchi",
        position_en: "developer",
        text_ru: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_uz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_oz: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        text_en: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mini veniam, quis nostrud exercitation ullamco laboris",
        signature: "../assets/images/signature.png"
    }
]

